name: xarray-docs
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy=1.15
  - scipy=1.1.0
  - numba=0.40.0
  - matplotlib=2.2.2
  - nbsphinx=0.3.5
  - sphinx=1.8.1
  - numpydoc=0.8.0
  - pandoc
  - nbconvert!=5.4
  - ipykernel
  - matplotlib
  - graphviz
  - python-graphviz